ministryofjustice/dps-gradle-spring-boot

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/DpsSpringBootPlugin.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/DpsSpringBootPluginFuncTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/DpsSpringBootPluginTest.kt
And switch unit test to normal testing stack
=> DT-727 Add a functional test

.circleci/config.yml, build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/DpsSpringBootPlugin.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/DpsSpringBootPluginFuncTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/DpsSpringBootPluginTest.kt
* In the functional test only run the build once
* Move all code from the old functional test's gradle build into the plugin
* Add circle build
=> DT-727 gradle plugin

release-notes/1.1.2.md
Update 1.1.2 release notes to include properties file workaround.
=> 1.1.2 release note updates

README.md, build.gradle.kts, release-notes/2.1.1.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/BaseConfigManager.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/functional/ProjectRunner.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/functional/pluginmanagers/SpringBootPluginManagerTest.kt
=> DT-1420 junit 4

README.md, build.gradle.kts, release-notes/3.3.14.md, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/BaseConfigManagerTest.kt
https://dsdmoj.atlassian.net/browse/DT-2912
=> DT-2912: upgrade to Kotlin 1.6

README.md, build.gradle.kts, release-notes/3.4.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManager.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManagerTest.kt
Reverts ministryofjustice/dps-gradle-spring-boot#122
=> Revert "DT-2952: upgrade com.nhaarman.mockitokotlin2 2.2.0 to org.mockito.kotlin 4.0.0"

README.md, build.gradle.kts, release-notes/4.0.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/AppInsightsConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/BaseConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManager.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManagerTest.kt
This reverts commit 044e6e01ce3a3e94dccde5d778c997b31803498d.
=> Revert "Revert "DT 2989 reapply revert (#126)" (#127)"

.circleci/config.yml
https://dsdmoj.atlassian.net/browse/HAAR-271
=> HAAR-271: use latest hmpps-orb to fix dependency-check database issue

README.md, build.gradle.kts, release-notes/4.2.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManager.kt, src/main/resources/dps-gradle-spring-boot-suppressions.xml
- org.springframework.boot:spring-boot-gradle-plugin [2.6.7 -> 2.7.0]
- https://spring.io/blog/2022/05/19/spring-boot-2-7-0-available-now
- com.fasterxml.jackson.module:jackson-module-kotlin [2.13.2 -> 2.13.3]
- CVE-2016-1000027
=> DSE-242: ⬆️  Upgraded to SB 2.7.0

README.md
=> Group Release Notes by major version

README.md, build.gradle.kts, release-notes/4.5.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/AppInsightsConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/BaseConfigManager.kt, src/main/resources/dps-gradle-spring-boot-suppressions.xml
- SDI-365: Suppress snakeyaml vuln
- SDI-362: Upgrade app insights
=> SDI-362: snakeyaml suppression and upgrade application insights

build.gradle.kts, release-notes/4.8.0.md, src/main/resources/dps-gradle-spring-boot-suppressions.xml
- SDI-528: 🔒️ Suppress false positives for fredsmith utils
=> SDI-528: 🔒️ Suppress false positives for fredsmith utils

build.gradle.kts, release-notes/5.0.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/AppInsightsConfigManager.kt, src/main/resources/dps-gradle-spring-boot-suppressions.xml
- SDI-528: ⬆  Bump owasp for database column error
=> SDI-528: ⬆ Bump owasp for database column error

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/AppInsightsConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/BaseConfigManager.kt
- SDI-528: ⬆  Bump to latest spring boot
=> SDI-528: ⬆  Bump to latest spring boot

README.md, build.gradle.kts, release-notes/4.8.1.md, release-notes/4.8.2.md, release-notes/5.0.1.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/AppInsightsConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManager.kt, src/main/resources/dps-gradle-spring-boot-suppressions.xml
- SDI-477: ✨ Upgrades and suppressions
=> SDI-477: ✨ Upgrades and suppressions

README.md, build.gradle.kts, release-notes/5.1.0.md
- SDI-477: ⬆  Bump to kotlin 1.8.10
=> SDI-477: ⬆ Bump to kotlin 1.8.10

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/AppInsightsConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/DependencyManagementPluginManager.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/DependencyManagementPluginManagerNettyTest.kt
- SDIT-513: 🐛 Fix opentelemetry version pinning and remove netty pinning
=> SDIT-513: 🐛 Fix opentelemetry version pinning and remove netty pinning

README.md, build.gradle.kts, release-notes/4.8.4.md, release-notes/5.1.1.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/DependencyCheckPluginManager.kt, src/main/resources/.trivyignore, src/main/resources/dps-gradle-spring-boot-suppressions.xml
- SDIT-513: ⬆️  Upgrade to latest to fix owasp issues
=> SDIT-513: ⬆️ Upgrade to latest to fix owasp issues

build.gradle.kts
- SDIT-703: ⬆️  Upgrade to latest spring boot etc.
=> SDIT-703: ⬆️  Upgrade to latest spring boot etc.

build.gradle.kts
=>  SDIT-747: 🔖 Release plugin

README.md, build.gradle.kts, release-notes/4.8.7.md, release-notes/5.2.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/AppInsightsConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/BaseConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManager.kt
- SDIT-822: ⬆️ Upgrade to latest spring boot 3
=> SDIT-822: ⬆️ Upgrade to latest spring boot 3

README.md, build.gradle.kts, release-notes/4.8.8.md, release-notes/5.2.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/BaseConfigManager.kt
- SDIT-822: ⬆️ Upgrade to latest guava for cve
=> SDIT-822: ⬆️ Upgrade to latest guava for cve

README.md, build.gradle.kts, release-notes/4.9.1.md, release-notes/5.2.2.md, src/main/resources/dps-gradle-spring-boot-suppressions.xml
- SDIT-903: 🔒️ Suppress false positive jackson issue
=> SDIT-903: 🔒️ Suppress false positive jackson issue

README.md, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, release-notes/4.11.0.md, release-notes/5.4.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/AppInsightsConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/configmanagers/BaseConfigManager.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManager.kt, src/main/resources/dps-gradle-spring-boot-suppressions.xml
- SDIT-1061: ⬆️ Spring boot and other upgrades
=> SDIT-1061: ⬆️ Spring boot and other upgrades

README.md, build.gradle.kts, release-notes/4.13.0.md, release-notes/5.7.0.md, src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/pluginmanagers/KotlinPluginManager.kt
- SDIT-1164: 🔒️ Upgrade to 3.1.5 for tomcat vulnerabilities
=> SDIT-1164: 🔒️ Upgrade to 3.1.5 for tomcat vulnerabilities

release-notes/6.x.md
A change of config to fix a build  error when upgrading a project's gradle-spring-boot plugin to 6.0.0 and above
=> MAP-1462 update realease notes
